[2024-05-30T12:19:42.237+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-30T12:19:42.261+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stored_procedures.insert_uuid manual__2024-05-30T12:19:38.718232+00:00 [queued]>
[2024-05-30T12:19:42.271+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stored_procedures.insert_uuid manual__2024-05-30T12:19:38.718232+00:00 [queued]>
[2024-05-30T12:19:42.272+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-30T12:19:42.286+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): insert_uuid> on 2024-05-30 12:19:38.718232+00:00
[2024-05-30T12:19:42.293+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1196) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-30T12:19:42.296+0000] {standard_task_runner.py:63} INFO - Started process 1198 to run task
[2024-05-30T12:19:42.294+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stored_procedures', 'insert_uuid', 'manual__2024-05-30T12:19:38.718232+00:00', '--job-id', '357', '--raw', '--subdir', 'DAGS_FOLDER/dag_example.py', '--cfg-path', '/tmp/tmpqduwi6v0']
[2024-05-30T12:19:42.298+0000] {standard_task_runner.py:91} INFO - Job 357: Subtask insert_uuid
[2024-05-30T12:19:42.354+0000] {task_command.py:426} INFO - Running <TaskInstance: stored_procedures.insert_uuid manual__2024-05-30T12:19:38.718232+00:00 [running]> on host 29c09f03cc50
[2024-05-30T12:19:42.452+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yamin' AIRFLOW_CTX_DAG_ID='stored_procedures' AIRFLOW_CTX_TASK_ID='insert_uuid' AIRFLOW_CTX_EXECUTION_DATE='2024-05-30T12:19:38.718232+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-30T12:19:38.718232+00:00'
[2024-05-30T12:19:42.453+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-30T12:19:42.466+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-30T12:19:42.468+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: generate_uuid() takes 0 positional arguments but 1 was given
[2024-05-30T12:19:42.484+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=stored_procedures, task_id=insert_uuid, execution_date=20240530T121938, start_date=20240530T121942, end_date=20240530T121942
[2024-05-30T12:19:42.500+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 357 for task insert_uuid (generate_uuid() takes 0 positional arguments but 1 was given; 1198)
[2024-05-30T12:19:42.512+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-30T12:19:42.545+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-30T12:19:42.547+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
