[2024-05-30T12:20:24.757+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-30T12:20:24.779+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stored_procedures.bash_task_start manual__2024-05-30T12:20:23.350307+00:00 [queued]>
[2024-05-30T12:20:24.788+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stored_procedures.bash_task_start manual__2024-05-30T12:20:23.350307+00:00 [queued]>
[2024-05-30T12:20:24.789+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-30T12:20:24.803+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): bash_task_start> on 2024-05-30 12:20:23.350307+00:00
[2024-05-30T12:20:24.809+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1213) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-30T12:20:24.811+0000] {standard_task_runner.py:63} INFO - Started process 1215 to run task
[2024-05-30T12:20:24.810+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stored_procedures', 'bash_task_start', 'manual__2024-05-30T12:20:23.350307+00:00', '--job-id', '358', '--raw', '--subdir', 'DAGS_FOLDER/dag_example.py', '--cfg-path', '/tmp/tmpi5fy2zaq']
[2024-05-30T12:20:24.813+0000] {standard_task_runner.py:91} INFO - Job 358: Subtask bash_task_start
[2024-05-30T12:20:24.870+0000] {task_command.py:426} INFO - Running <TaskInstance: stored_procedures.bash_task_start manual__2024-05-30T12:20:23.350307+00:00 [running]> on host 29c09f03cc50
[2024-05-30T12:20:24.964+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yamin' AIRFLOW_CTX_DAG_ID='stored_procedures' AIRFLOW_CTX_TASK_ID='bash_task_start' AIRFLOW_CTX_EXECUTION_DATE='2024-05-30T12:20:23.350307+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-30T12:20:23.350307+00:00'
[2024-05-30T12:20:24.966+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-30T12:20:24.979+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-30T12:20:24.981+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Here is your bash message at the start pf your DAG, your workflow has started !"']
[2024-05-30T12:20:24.991+0000] {subprocess.py:86} INFO - Output:
[2024-05-30T12:20:24.993+0000] {subprocess.py:93} INFO - Here is your bash message at the start pf your DAG, your workflow has started !
[2024-05-30T12:20:24.993+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-30T12:20:24.995+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-30T12:20:25.024+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=stored_procedures, task_id=bash_task_start, execution_date=20240530T122023, start_date=20240530T122024, end_date=20240530T122025
[2024-05-30T12:20:25.066+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-30T12:20:25.095+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-30T12:20:25.099+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
