[2024-05-28T14:50:50.809+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T14:50:50.833+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stored_procedures.python_task_2 manual__2024-05-28T14:50:47.176680+00:00 [queued]>
[2024-05-28T14:50:50.843+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stored_procedures.python_task_2 manual__2024-05-28T14:50:47.176680+00:00 [queued]>
[2024-05-28T14:50:50.844+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-28T14:50:50.858+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): python_task_2> on 2024-05-28 14:50:47.176680+00:00
[2024-05-28T14:50:50.867+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=742) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-28T14:50:50.868+0000] {standard_task_runner.py:63} INFO - Started process 744 to run task
[2024-05-28T14:50:50.869+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stored_procedures', 'python_task_2', 'manual__2024-05-28T14:50:47.176680+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/dag_example.py', '--cfg-path', '/tmp/tmppmozdb9b']
[2024-05-28T14:50:50.871+0000] {standard_task_runner.py:91} INFO - Job 88: Subtask python_task_2
[2024-05-28T14:50:50.919+0000] {task_command.py:426} INFO - Running <TaskInstance: stored_procedures.python_task_2 manual__2024-05-28T14:50:47.176680+00:00 [running]> on host 29c09f03cc50
[2024-05-28T14:50:51.006+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yamin' AIRFLOW_CTX_DAG_ID='stored_procedures' AIRFLOW_CTX_TASK_ID='python_task_2' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T14:50:47.176680+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-28T14:50:47.176680+00:00'
[2024-05-28T14:50:51.008+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T14:50:51.109+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-28T14:50:51.110+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T14:50:51.121+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=stored_procedures, task_id=python_task_2, execution_date=20240528T145047, start_date=20240528T145050, end_date=20240528T145051
[2024-05-28T14:50:51.164+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-28T14:50:51.186+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-28T14:50:51.188+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
